version: '3.4'
services:
    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        networks:
            - frontend-network
            - backend-network
        depends_on: 
            - mysql
        restart: always
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - backend-network
        restart: always
    apache: 
        build: ./apache
        ports: 
            - 80:80
        depends_on: 
            - mysql
        networks: 
            - frontend-network
            - backend-network
        restart: always
networks:
    frontend-network:
    backend-network:

volumes:
    mysql_data:
